# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1299, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1281, 861))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1251, 741))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(380, 50, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(380, 80, 41, 16))
        self.label_2.setObjectName("label_2")
        self.findClientTelField = QtWidgets.QLineEdit(self.groupBox)
        self.findClientTelField.setGeometry(QtCore.QRect(440, 50, 321, 20))
        self.findClientTelField.setMaxLength(20)
        self.findClientTelField.setObjectName("findClientTelField")
        self.findClientNameField = QtWidgets.QLineEdit(self.groupBox)
        self.findClientNameField.setGeometry(QtCore.QRect(440, 80, 321, 20))
        self.findClientNameField.setText("")
        self.findClientNameField.setMaxLength(40)
        self.findClientNameField.setObjectName("findClientNameField")
        self.findClientButton = QtWidgets.QPushButton(self.groupBox)
        self.findClientButton.setEnabled(False)
        self.findClientButton.setGeometry(QtCore.QRect(770, 50, 75, 23))
        self.findClientButton.setObjectName("findClientButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 1231, 381))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(100, 30, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(200, 30, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(990, 30, 41, 16))
        self.label_6.setObjectName("label_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 260, 1141, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.articlesNumberField = QtWidgets.QSpinBox(self.groupBox_3)
        self.articlesNumberField.setGeometry(QtCore.QRect(10, 40, 42, 22))
        self.articlesNumberField.setFocusPolicy(QtCore.Qt.NoFocus)
        self.articlesNumberField.setReadOnly(False)
        self.articlesNumberField.setMinimum(1)
        self.articlesNumberField.setMaximum(999)
        self.articlesNumberField.setObjectName("articlesNumberField")
        self.articleServiceField = QtWidgets.QComboBox(self.groupBox_3)
        self.articleServiceField.setEnabled(True)
        self.articleServiceField.setGeometry(QtCore.QRect(80, 40, 161, 22))
        self.articleServiceField.setObjectName("articleServiceField")
        self.articleDescriptionField = QtWidgets.QLineEdit(self.groupBox_3)
        self.articleDescriptionField.setGeometry(QtCore.QRect(250, 40, 711, 20))
        self.articleDescriptionField.setMaxLength(80)
        self.articleDescriptionField.setObjectName("articleDescriptionField")
        self.articleUnitValueField = QtWidgets.QLineEdit(self.groupBox_3)
        self.articleUnitValueField.setGeometry(QtCore.QRect(970, 40, 161, 20))
        self.articleUnitValueField.setMaxLength(12)
        self.articleUnitValueField.setObjectName("articleUnitValueField")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(80, 20, 61, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(250, 20, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(970, 20, 71, 16))
        self.label_10.setObjectName("label_10")
        self.addArticleButton = QtWidgets.QPushButton(self.groupBox_3)
        self.addArticleButton.setEnabled(False)
        self.addArticleButton.setGeometry(QtCore.QRect(530, 70, 75, 23))
        self.addArticleButton.setObjectName("addArticleButton")
        self.removeArticleButton = QtWidgets.QPushButton(self.groupBox_2)
        self.removeArticleButton.setEnabled(False)
        self.removeArticleButton.setGeometry(QtCore.QRect(1180, 50, 31, 23))
        self.removeArticleButton.setObjectName("removeArticleButton")
        self.articlesTable = QtWidgets.QTableWidget(self.groupBox_2)
        self.articlesTable.setEnabled(True)
        self.articlesTable.setGeometry(QtCore.QRect(30, 50, 1141, 151))
        self.articlesTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.articlesTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.articlesTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.articlesTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.articlesTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.articlesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.articlesTable.setRowCount(0)
        self.articlesTable.setColumnCount(4)
        self.articlesTable.setObjectName("articlesTable")
        self.articlesTable.horizontalHeader().setVisible(False)
        self.articlesTable.verticalHeader().setVisible(False)
        self.totalArticlesField = QtWidgets.QLineEdit(self.groupBox_2)
        self.totalArticlesField.setGeometry(QtCore.QRect(460, 220, 271, 20))
        self.totalArticlesField.setReadOnly(True)
        self.totalArticlesField.setObjectName("totalArticlesField")
        self.label_51 = QtWidgets.QLabel(self.groupBox_2)
        self.label_51.setGeometry(QtCore.QRect(370, 220, 71, 20))
        self.label_51.setObjectName("label_51")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(490, 580, 31, 16))
        self.label_12.setObjectName("label_12")
        self.depositField = QtWidgets.QLineEdit(self.groupBox)
        self.depositField.setGeometry(QtCore.QRect(530, 580, 161, 20))
        self.depositField.setMaxLength(12)
        self.depositField.setObjectName("depositField")
        self.balanceField = QtWidgets.QLineEdit(self.groupBox)
        self.balanceField.setEnabled(True)
        self.balanceField.setGeometry(QtCore.QRect(530, 620, 161, 20))
        self.balanceField.setReadOnly(True)
        self.balanceField.setObjectName("balanceField")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(490, 620, 31, 16))
        self.label_13.setObjectName("label_13")
        self.generateBillButton = QtWidgets.QPushButton(self.groupBox)
        self.generateBillButton.setEnabled(False)
        self.generateBillButton.setGeometry(QtCore.QRect(530, 650, 151, 31))
        self.generateBillButton.setObjectName("generateBillButton")
        self.totalField = QtWidgets.QLineEdit(self.groupBox)
        self.totalField.setGeometry(QtCore.QRect(530, 540, 161, 20))
        self.totalField.setReadOnly(True)
        self.totalField.setObjectName("totalField")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(490, 540, 31, 16))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 1251, 771))
        self.groupBox_4.setObjectName("groupBox_4")
        self.findBillField = QtWidgets.QLineEdit(self.groupBox_4)
        self.findBillField.setGeometry(QtCore.QRect(560, 20, 161, 20))
        self.findBillField.setMaxLength(15)
        self.findBillField.setObjectName("findBillField")
        self.findBillButton = QtWidgets.QPushButton(self.groupBox_4)
        self.findBillButton.setEnabled(False)
        self.findBillButton.setGeometry(QtCore.QRect(740, 20, 75, 23))
        self.findBillButton.setObjectName("findBillButton")
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        self.label_40.setGeometry(QtCore.QRect(460, 20, 91, 20))
        self.label_40.setObjectName("label_40")
        self.billCodeField = QtWidgets.QLineEdit(self.groupBox_4)
        self.billCodeField.setGeometry(QtCore.QRect(554, 50, 161, 20))
        self.billCodeField.setReadOnly(True)
        self.billCodeField.setObjectName("billCodeField")
        self.label_41 = QtWidgets.QLabel(self.groupBox_4)
        self.label_41.setGeometry(QtCore.QRect(510, 50, 41, 20))
        self.label_41.setObjectName("label_41")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_9.setGeometry(QtCore.QRect(80, 100, 1051, 91))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_42 = QtWidgets.QLabel(self.groupBox_9)
        self.label_42.setGeometry(QtCore.QRect(340, 20, 51, 20))
        self.label_42.setObjectName("label_42")
        self.telField = QtWidgets.QLineEdit(self.groupBox_9)
        self.telField.setGeometry(QtCore.QRect(430, 20, 271, 20))
        self.telField.setText("")
        self.telField.setReadOnly(True)
        self.telField.setObjectName("telField")
        self.label_43 = QtWidgets.QLabel(self.groupBox_9)
        self.label_43.setGeometry(QtCore.QRect(340, 60, 51, 20))
        self.label_43.setObjectName("label_43")
        self.nameField = QtWidgets.QLineEdit(self.groupBox_9)
        self.nameField.setGeometry(QtCore.QRect(430, 60, 271, 20))
        self.nameField.setText("")
        self.nameField.setReadOnly(True)
        self.nameField.setObjectName("nameField")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_10.setGeometry(QtCore.QRect(80, 370, 1051, 281))
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.queryDepositField = QtWidgets.QLineEdit(self.groupBox_10)
        self.queryDepositField.setGeometry(QtCore.QRect(420, 190, 121, 20))
        self.queryDepositField.setReadOnly(True)
        self.queryDepositField.setObjectName("queryDepositField")
        self.label_45 = QtWidgets.QLabel(self.groupBox_10)
        self.label_45.setGeometry(QtCore.QRect(370, 190, 31, 20))
        self.label_45.setObjectName("label_45")
        self.queryTotalField = QtWidgets.QLineEdit(self.groupBox_10)
        self.queryTotalField.setGeometry(QtCore.QRect(420, 160, 271, 20))
        self.queryTotalField.setReadOnly(True)
        self.queryTotalField.setObjectName("queryTotalField")
        self.label_44 = QtWidgets.QLabel(self.groupBox_10)
        self.label_44.setGeometry(QtCore.QRect(350, 160, 51, 20))
        self.label_44.setObjectName("label_44")
        self.label_46 = QtWidgets.QLabel(self.groupBox_10)
        self.label_46.setGeometry(QtCore.QRect(300, 250, 101, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.queryBalanceField = QtWidgets.QLineEdit(self.groupBox_10)
        self.queryBalanceField.setGeometry(QtCore.QRect(420, 250, 271, 20))
        self.queryBalanceField.setReadOnly(True)
        self.queryBalanceField.setObjectName("queryBalanceField")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 10, 1011, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.partialBalanceField = QtWidgets.QLineEdit(self.groupBox_5)
        self.partialBalanceField.setGeometry(QtCore.QRect(400, 110, 271, 20))
        self.partialBalanceField.setReadOnly(True)
        self.partialBalanceField.setObjectName("partialBalanceField")
        self.label_52 = QtWidgets.QLabel(self.groupBox_5)
        self.label_52.setGeometry(QtCore.QRect(200, 110, 181, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.depositForCancelationAfterArticleRemovalField = QtWidgets.QLineEdit(self.groupBox_5)
        self.depositForCancelationAfterArticleRemovalField.setGeometry(QtCore.QRect(400, 50, 271, 20))
        self.depositForCancelationAfterArticleRemovalField.setReadOnly(True)
        self.depositForCancelationAfterArticleRemovalField.setObjectName("depositForCancelationAfterArticleRemovalField")
        self.label_53 = QtWidgets.QLabel(self.groupBox_5)
        self.label_53.setGeometry(QtCore.QRect(200, 50, 191, 20))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.groupBox_5)
        self.label_54.setGeometry(QtCore.QRect(250, 20, 141, 20))
        self.label_54.setObjectName("label_54")
        self.removedArticlesValueField = QtWidgets.QLineEdit(self.groupBox_5)
        self.removedArticlesValueField.setGeometry(QtCore.QRect(400, 20, 271, 20))
        self.removedArticlesValueField.setReadOnly(True)
        self.removedArticlesValueField.setObjectName("removedArticlesValueField")
        self.balanceAfterPartialCancelationField = QtWidgets.QLineEdit(self.groupBox_5)
        self.balanceAfterPartialCancelationField.setGeometry(QtCore.QRect(400, 80, 271, 20))
        self.balanceAfterPartialCancelationField.setReadOnly(True)
        self.balanceAfterPartialCancelationField.setObjectName("balanceAfterPartialCancelationField")
        self.label_55 = QtWidgets.QLabel(self.groupBox_5)
        self.label_55.setGeometry(QtCore.QRect(250, 80, 141, 20))
        self.label_55.setObjectName("label_55")
        self.queryDepositForCancelationField = QtWidgets.QLineEdit(self.groupBox_10)
        self.queryDepositForCancelationField.setGeometry(QtCore.QRect(420, 220, 271, 20))
        self.queryDepositForCancelationField.setReadOnly(True)
        self.queryDepositForCancelationField.setObjectName("queryDepositForCancelationField")
        self.label_56 = QtWidgets.QLabel(self.groupBox_10)
        self.label_56.setGeometry(QtCore.QRect(240, 220, 171, 20))
        self.label_56.setObjectName("label_56")
        self.queryIncreaseDepositField = QtWidgets.QLineEdit(self.groupBox_10)
        self.queryIncreaseDepositField.setEnabled(True)
        self.queryIncreaseDepositField.setGeometry(QtCore.QRect(560, 190, 131, 20))
        self.queryIncreaseDepositField.setReadOnly(False)
        self.queryIncreaseDepositField.setObjectName("queryIncreaseDepositField")
        self.increaseDepositButton = QtWidgets.QPushButton(self.groupBox_10)
        self.increaseDepositButton.setEnabled(False)
        self.increaseDepositButton.setGeometry(QtCore.QRect(540, 190, 21, 21))
        self.increaseDepositButton.setObjectName("increaseDepositButton")
        self.label_47 = QtWidgets.QLabel(self.groupBox_4)
        self.label_47.setGeometry(QtCore.QRect(410, 660, 51, 20))
        self.label_47.setObjectName("label_47")
        self.billStateField = QtWidgets.QLineEdit(self.groupBox_4)
        self.billStateField.setGeometry(QtCore.QRect(500, 660, 271, 20))
        self.billStateField.setText("")
        self.billStateField.setReadOnly(True)
        self.billStateField.setObjectName("billStateField")
        self.receivedMoneyField = QtWidgets.QLineEdit(self.groupBox_4)
        self.receivedMoneyField.setGeometry(QtCore.QRect(460, 700, 131, 20))
        self.receivedMoneyField.setObjectName("receivedMoneyField")
        self.changeField = QtWidgets.QLineEdit(self.groupBox_4)
        self.changeField.setGeometry(QtCore.QRect(620, 700, 131, 20))
        self.changeField.setReadOnly(True)
        self.changeField.setObjectName("changeField")
        self.label_48 = QtWidgets.QLabel(self.groupBox_4)
        self.label_48.setGeometry(QtCore.QRect(490, 680, 71, 20))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.groupBox_4)
        self.label_49.setGeometry(QtCore.QRect(660, 680, 41, 20))
        self.label_49.setObjectName("label_49")
        self.cancelBillButton = QtWidgets.QPushButton(self.groupBox_4)
        self.cancelBillButton.setEnabled(False)
        self.cancelBillButton.setGeometry(QtCore.QRect(340, 730, 111, 31))
        self.cancelBillButton.setObjectName("cancelBillButton")
        self.printBillButton = QtWidgets.QPushButton(self.groupBox_4)
        self.printBillButton.setEnabled(False)
        self.printBillButton.setGeometry(QtCore.QRect(610, 730, 111, 31))
        self.printBillButton.setObjectName("printBillButton")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(100, 200, 31, 16))
        self.label_17.setObjectName("label_17")
        self.consultArticlesTable = QtWidgets.QTableWidget(self.groupBox_4)
        self.consultArticlesTable.setEnabled(True)
        self.consultArticlesTable.setGeometry(QtCore.QRect(40, 220, 1141, 111))
        self.consultArticlesTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.consultArticlesTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.consultArticlesTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.consultArticlesTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.consultArticlesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.consultArticlesTable.setRowCount(0)
        self.consultArticlesTable.setColumnCount(6)
        self.consultArticlesTable.setObjectName("consultArticlesTable")
        self.consultArticlesTable.horizontalHeader().setVisible(False)
        self.consultArticlesTable.verticalHeader().setVisible(False)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(250, 200, 61, 16))
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(910, 200, 41, 16))
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(150, 200, 41, 16))
        self.label_16.setObjectName("label_16")
        self.partialCancelationButton = QtWidgets.QPushButton(self.groupBox_4)
        self.partialCancelationButton.setEnabled(False)
        self.partialCancelationButton.setGeometry(QtCore.QRect(470, 730, 121, 31))
        self.partialCancelationButton.setObjectName("partialCancelationButton")
        self.removeConsultArticleButton = QtWidgets.QPushButton(self.groupBox_4)
        self.removeConsultArticleButton.setEnabled(False)
        self.removeConsultArticleButton.setGeometry(QtCore.QRect(1190, 220, 31, 23))
        self.removeConsultArticleButton.setObjectName("removeConsultArticleButton")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(1090, 200, 41, 16))
        self.label_18.setObjectName("label_18")
        self.queryTotalArticlesField = QtWidgets.QLineEdit(self.groupBox_4)
        self.queryTotalArticlesField.setGeometry(QtCore.QRect(510, 340, 271, 20))
        self.queryTotalArticlesField.setReadOnly(True)
        self.queryTotalArticlesField.setObjectName("queryTotalArticlesField")
        self.label_50 = QtWidgets.QLabel(self.groupBox_4)
        self.label_50.setGeometry(QtCore.QRect(420, 340, 71, 20))
        self.label_50.setObjectName("label_50")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(40, 200, 51, 16))
        self.label_19.setObjectName("label_19")
        self.generationDateField = QtWidgets.QLineEdit(self.groupBox_4)
        self.generationDateField.setGeometry(QtCore.QRect(434, 80, 161, 20))
        self.generationDateField.setText("")
        self.generationDateField.setReadOnly(True)
        self.generationDateField.setObjectName("generationDateField")
        self.label_57 = QtWidgets.QLabel(self.groupBox_4)
        self.label_57.setGeometry(QtCore.QRect(320, 80, 101, 20))
        self.label_57.setObjectName("label_57")
        self.undoBillButton = QtWidgets.QPushButton(self.groupBox_4)
        self.undoBillButton.setEnabled(False)
        self.undoBillButton.setGeometry(QtCore.QRect(740, 730, 111, 31))
        self.undoBillButton.setObjectName("undoBillButton")
        self.label_63 = QtWidgets.QLabel(self.groupBox_4)
        self.label_63.setGeometry(QtCore.QRect(616, 80, 101, 20))
        self.label_63.setObjectName("label_63")
        self.cancelationDateField = QtWidgets.QLineEdit(self.groupBox_4)
        self.cancelationDateField.setGeometry(QtCore.QRect(730, 80, 161, 20))
        self.cancelationDateField.setText("")
        self.cancelationDateField.setReadOnly(True)
        self.cancelationDateField.setObjectName("cancelationDateField")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.filterBillsTable = QtWidgets.QTableWidget(self.tab_5)
        self.filterBillsTable.setEnabled(True)
        self.filterBillsTable.setGeometry(QtCore.QRect(400, 150, 871, 431))
        self.filterBillsTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.filterBillsTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.filterBillsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.filterBillsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.filterBillsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.filterBillsTable.setRowCount(0)
        self.filterBillsTable.setColumnCount(10)
        self.filterBillsTable.setObjectName("filterBillsTable")
        self.filterBillsTable.horizontalHeader().setVisible(False)
        self.filterBillsTable.verticalHeader().setVisible(False)
        self.filterClientsPhoneField = QtWidgets.QLineEdit(self.tab_5)
        self.filterClientsPhoneField.setGeometry(QtCore.QRect(10, 90, 121, 20))
        self.filterClientsPhoneField.setMaxLength(15)
        self.filterClientsPhoneField.setObjectName("filterClientsPhoneField")
        self.filterClientsNameField = QtWidgets.QLineEdit(self.tab_5)
        self.filterClientsNameField.setGeometry(QtCore.QRect(130, 90, 211, 20))
        self.filterClientsNameField.setMaxLength(15)
        self.filterClientsNameField.setObjectName("filterClientsNameField")
        self.label_59 = QtWidgets.QLabel(self.tab_5)
        self.label_59.setGeometry(QtCore.QRect(130, 70, 41, 20))
        self.label_59.setObjectName("label_59")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 41, 16))
        self.label_20.setObjectName("label_20")
        self.label_58 = QtWidgets.QLabel(self.tab_5)
        self.label_58.setGeometry(QtCore.QRect(150, 40, 101, 20))
        self.label_58.setObjectName("label_58")
        self.label_60 = QtWidgets.QLabel(self.tab_5)
        self.label_60.setGeometry(QtCore.QRect(780, 50, 101, 20))
        self.label_60.setObjectName("label_60")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(460, 70, 91, 16))
        self.label_21.setObjectName("label_21")
        self.filterBillsPhoneField = QtWidgets.QLineEdit(self.tab_5)
        self.filterBillsPhoneField.setGeometry(QtCore.QRect(460, 90, 101, 20))
        self.filterBillsPhoneField.setMaxLength(15)
        self.filterBillsPhoneField.setReadOnly(False)
        self.filterBillsPhoneField.setObjectName("filterBillsPhoneField")
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        self.label_28.setGeometry(QtCore.QRect(10, 130, 41, 16))
        self.label_28.setObjectName("label_28")
        self.label_62 = QtWidgets.QLabel(self.tab_5)
        self.label_62.setGeometry(QtCore.QRect(130, 130, 41, 16))
        self.label_62.setObjectName("label_62")
        self.label_61 = QtWidgets.QLabel(self.tab_5)
        self.label_61.setGeometry(QtCore.QRect(400, 130, 41, 16))
        self.label_61.setObjectName("label_61")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(460, 130, 51, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(560, 130, 16, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(590, 130, 41, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(680, 130, 41, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_5)
        self.label_26.setGeometry(QtCore.QRect(770, 130, 81, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(860, 130, 41, 16))
        self.label_27.setObjectName("label_27")
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(950, 130, 41, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(1050, 130, 61, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setGeometry(QtCore.QRect(1160, 130, 61, 16))
        self.label_31.setObjectName("label_31")
        self.filterBillsButton = QtWidgets.QPushButton(self.tab_5)
        self.filterBillsButton.setEnabled(False)
        self.filterBillsButton.setGeometry(QtCore.QRect(370, 330, 31, 31))
        self.filterBillsButton.setObjectName("filterBillsButton")
        self.filterClientsTable = QtWidgets.QTableWidget(self.tab_5)
        self.filterClientsTable.setEnabled(True)
        self.filterClientsTable.setGeometry(QtCore.QRect(10, 150, 361, 431))
        self.filterClientsTable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.filterClientsTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.filterClientsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.filterClientsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.filterClientsTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.filterClientsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.filterClientsTable.setRowCount(0)
        self.filterClientsTable.setColumnCount(2)
        self.filterClientsTable.setObjectName("filterClientsTable")
        self.filterClientsTable.horizontalHeader().setVisible(False)
        self.filterClientsTable.horizontalHeader().setSortIndicatorShown(True)
        self.filterClientsTable.verticalHeader().setVisible(False)
        self.filterClientsTable.verticalHeader().setSortIndicatorShown(False)
        self.label_32 = QtWidgets.QLabel(self.tab_5)
        self.label_32.setGeometry(QtCore.QRect(950, 70, 91, 16))
        self.label_32.setObjectName("label_32")
        self.filterBillsStateField = QtWidgets.QComboBox(self.tab_5)
        self.filterBillsStateField.setEnabled(True)
        self.filterBillsStateField.setGeometry(QtCore.QRect(950, 90, 101, 22))
        self.filterBillsStateField.setObjectName("filterBillsStateField")
        self.filterBillsTotalField = QtWidgets.QLineEdit(self.tab_5)
        self.filterBillsTotalField.setGeometry(QtCore.QRect(590, 590, 91, 20))
        self.filterBillsTotalField.setReadOnly(True)
        self.filterBillsTotalField.setObjectName("filterBillsTotalField")
        self.filterBillsDepositField = QtWidgets.QLineEdit(self.tab_5)
        self.filterBillsDepositField.setGeometry(QtCore.QRect(680, 590, 91, 20))
        self.filterBillsDepositField.setReadOnly(True)
        self.filterBillsDepositField.setObjectName("filterBillsDepositField")
        self.filterBillsDepositForCancelationField = QtWidgets.QLineEdit(self.tab_5)
        self.filterBillsDepositForCancelationField.setGeometry(QtCore.QRect(770, 590, 91, 20))
        self.filterBillsDepositForCancelationField.setReadOnly(True)
        self.filterBillsDepositForCancelationField.setObjectName("filterBillsDepositForCancelationField")
        self.filterBillsBalanceField = QtWidgets.QLineEdit(self.tab_5)
        self.filterBillsBalanceField.setGeometry(QtCore.QRect(860, 590, 91, 20))
        self.filterBillsBalanceField.setReadOnly(True)
        self.filterBillsBalanceField.setObjectName("filterBillsBalanceField")
        self.filterBillsNumberField = QtWidgets.QLineEdit(self.tab_5)
        self.filterBillsNumberField.setGeometry(QtCore.QRect(560, 590, 31, 20))
        self.filterBillsNumberField.setReadOnly(True)
        self.filterBillsNumberField.setObjectName("filterBillsNumberField")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1299, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SISTEMA DE FACTURACIÓN"))
        self.groupBox.setTitle(_translate("MainWindow", "DETALLE DE FACTURA"))
        self.label.setText(_translate("MainWindow", "Teléfono"))
        self.label_2.setText(_translate("MainWindow", "Nombre"))
        self.findClientButton.setText(_translate("MainWindow", "Buscar"))
        self.groupBox_2.setTitle(_translate("MainWindow", "DETALLE DE ARTICULOS"))
        self.label_3.setText(_translate("MainWindow", "Cantidad"))
        self.label_4.setText(_translate("MainWindow", "Servicio"))
        self.label_5.setText(_translate("MainWindow", "Descripción"))
        self.label_6.setText(_translate("MainWindow", "Valor"))
        self.groupBox_3.setTitle(_translate("MainWindow", "AGREGAR ARTÍCULO"))
        self.articleUnitValueField.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Cantidad"))
        self.label_8.setText(_translate("MainWindow", "Servicio"))
        self.label_9.setText(_translate("MainWindow", "Descripción"))
        self.label_10.setText(_translate("MainWindow", "Valor unitario"))
        self.addArticleButton.setText(_translate("MainWindow", "Agregar"))
        self.removeArticleButton.setText(_translate("MainWindow", "X"))
        self.articlesTable.setSortingEnabled(True)
        self.totalArticlesField.setText(_translate("MainWindow", "0"))
        self.label_51.setText(_translate("MainWindow", "Total artículos"))
        self.label_12.setText(_translate("MainWindow", "Abono"))
        self.depositField.setText(_translate("MainWindow", "0"))
        self.balanceField.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "Saldo"))
        self.generateBillButton.setText(_translate("MainWindow", "GENERAR FACTURA"))
        self.totalField.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Total"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Generar Factura"))
        self.groupBox_4.setTitle(_translate("MainWindow", "DETALLE DE CONSULTA"))
        self.findBillButton.setText(_translate("MainWindow", "Consultar"))
        self.label_40.setText(_translate("MainWindow", "Código de factura"))
        self.label_41.setText(_translate("MainWindow", "Código"))
        self.groupBox_9.setTitle(_translate("MainWindow", "DATOS DEL CLIENTE"))
        self.label_42.setText(_translate("MainWindow", "Teléfono"))
        self.label_43.setText(_translate("MainWindow", "Nombre"))
        self.queryDepositField.setText(_translate("MainWindow", "0"))
        self.label_45.setText(_translate("MainWindow", "Abono"))
        self.queryTotalField.setText(_translate("MainWindow", "0"))
        self.label_44.setText(_translate("MainWindow", "Saldo total"))
        self.label_46.setText(_translate("MainWindow", "SALDO A CANCELAR"))
        self.queryBalanceField.setText(_translate("MainWindow", "0"))
        self.groupBox_5.setTitle(_translate("MainWindow", "CANCELACIÓN PARCIAL"))
        self.partialBalanceField.setText(_translate("MainWindow", "0"))
        self.label_52.setText(_translate("MainWindow", "SALDO A CANCELAR PARCIALMENTE"))
        self.depositForCancelationAfterArticleRemovalField.setText(_translate("MainWindow", "0"))
        self.label_53.setText(_translate("MainWindow", "Abono disponible luego de cancelación"))
        self.label_54.setText(_translate("MainWindow", "Valor de artículos a cancelar"))
        self.removedArticlesValueField.setText(_translate("MainWindow", "0"))
        self.balanceAfterPartialCancelationField.setText(_translate("MainWindow", "0"))
        self.label_55.setText(_translate("MainWindow", "Saldo luego de cancelación"))
        self.queryDepositForCancelationField.setText(_translate("MainWindow", "0"))
        self.label_56.setText(_translate("MainWindow", "Abono disponible para cancelación"))
        self.queryIncreaseDepositField.setText(_translate("MainWindow", "0"))
        self.increaseDepositButton.setText(_translate("MainWindow", "+"))
        self.label_47.setText(_translate("MainWindow", "ESTADO"))
        self.receivedMoneyField.setText(_translate("MainWindow", "0"))
        self.changeField.setText(_translate("MainWindow", "0"))
        self.label_48.setText(_translate("MainWindow", "Dinero recibido"))
        self.label_49.setText(_translate("MainWindow", "Cambio"))
        self.cancelBillButton.setText(_translate("MainWindow", "Cancelar factura"))
        self.printBillButton.setText(_translate("MainWindow", "Imprimir"))
        self.label_17.setText(_translate("MainWindow", "Cant"))
        self.consultArticlesTable.setSortingEnabled(True)
        self.label_15.setText(_translate("MainWindow", "Descripción"))
        self.label_14.setText(_translate("MainWindow", "Valor"))
        self.label_16.setText(_translate("MainWindow", "Servicio"))
        self.partialCancelationButton.setText(_translate("MainWindow", "Cancelar parcialmente"))
        self.removeConsultArticleButton.setText(_translate("MainWindow", "X"))
        self.label_18.setText(_translate("MainWindow", "Estado"))
        self.queryTotalArticlesField.setText(_translate("MainWindow", "0"))
        self.label_50.setText(_translate("MainWindow", "Total artículos"))
        self.label_19.setText(_translate("MainWindow", "Id"))
        self.label_57.setText(_translate("MainWindow", "Fecha de generación"))
        self.undoBillButton.setText(_translate("MainWindow", "Anular"))
        self.label_63.setText(_translate("MainWindow", "Fecha de cancelación"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Consultar Factura"))
        self.filterBillsTable.setSortingEnabled(True)
        self.label_59.setText(_translate("MainWindow", "Nombre"))
        self.label_20.setText(_translate("MainWindow", "Teléfono"))
        self.label_58.setText(_translate("MainWindow", "FILTRAR CLIENTES"))
        self.label_60.setText(_translate("MainWindow", "FILTRAR FACTURAS"))
        self.label_21.setText(_translate("MainWindow", "Teléfono(exacto)"))
        self.label_28.setText(_translate("MainWindow", "Teléfono"))
        self.label_62.setText(_translate("MainWindow", "Nombre"))
        self.label_61.setText(_translate("MainWindow", "Código"))
        self.label_22.setText(_translate("MainWindow", "Teléfono"))
        self.label_23.setText(_translate("MainWindow", "#"))
        self.label_24.setText(_translate("MainWindow", "Total"))
        self.label_25.setText(_translate("MainWindow", "Abono"))
        self.label_26.setText(_translate("MainWindow", "Abono can."))
        self.label_27.setText(_translate("MainWindow", "Saldo"))
        self.label_29.setText(_translate("MainWindow", "Estado"))
        self.label_30.setText(_translate("MainWindow", "Fecha gen."))
        self.label_31.setText(_translate("MainWindow", "Fecha can."))
        self.filterBillsButton.setText(_translate("MainWindow", "->"))
        self.filterClientsTable.setSortingEnabled(True)
        self.label_32.setText(_translate("MainWindow", "Estado"))
        self.filterBillsTotalField.setText(_translate("MainWindow", "0"))
        self.filterBillsDepositField.setText(_translate("MainWindow", "0"))
        self.filterBillsDepositForCancelationField.setText(_translate("MainWindow", "0"))
        self.filterBillsBalanceField.setText(_translate("MainWindow", "0"))
        self.filterBillsNumberField.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Clientes y Facturas"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Reportes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Configuración"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

